name: Tag New Versions

on:
  push:
    branches:
      - main

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2